# [[mgr.prepend_keymap]]
# on = [ "g", "1" ]
# run = "cd ~/.config"
# desc = "~/.config/"
#


[[mgr.prepend_keymap]]
on = [ "g", "<Space>"]
run = "noop"
# desc = "Jump interactively" 

[[mgr.prepend_keymap]]
on = [ "g", "d" ]
run = "cd ~/Documents/"
desc = "Go ~/Documents/"


[[mgr.prepend_keymap]]
on = ["<Space>"]
run = "cd --interactive"
desc = "Jump interactively" 
# [[mgr.prepend_keymap]]
# on = [ "g", "3" ]
# run = "cd ~/Downloads/"
# desc = "~/Downloads/"

[[mgr.prepend_keymap]]
on = [ "g", "p" ]
run = "cd ~/Pictures/"
desc = "Go ~/Pictures/"
#
# [[mgr.prepend_keymap]]
# on = [ "H" ]
# run = "cd ~"
# desc = "Home"

[[mgr.prepend_keymap]]
on  = ["M"]
run = "plugin mount"

[[mgr.prepend_keymap]]
on = [ "P", "s" ]
run = "plugin projects save"
desc = "Save current project"

[[mgr.prepend_keymap]]
on = [ "P", "l" ]
run = "plugin projects load"
desc = "Load project"

[[mgr.prepend_keymap]]
on = [ "P", "P" ]
run = "plugin projects load_last"
desc = "Load last project"

[[mgr.prepend_keymap]]
on = [ "P", "d" ]
run = "plugin projects delete"
desc = "Delete project"

[[mgr.prepend_keymap]]
on = [ "P", "D" ]
run = "plugin projects delete_all"
desc = "Delete all projects"

[[mgr.prepend_keymap]]
on = [ "P", "m" ]
run = "plugin projects 'merge current'"
desc = "Merge current tab to other projects"

[[mgr.prepend_keymap]]
on = [ "P", "M" ]
run = "plugin projects 'merge all'"
desc = "Merge current project to other projects"

[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"
